# Uncomment the next line to define a global platform for your project
platform :osx, '10.14'

target 'switchsoulmonarch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for switchsoulmonarch
  pod 'Magnet'

  target 'switchsoulmonarchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'switchsoulmonarchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

